# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WorkStation\pyqt\koco语音助手\index.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 744)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("koco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(730, 90, 561, 571))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 130, 111, 111))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 320, 111, 111))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 101, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 60, 241, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(4)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 4)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_2.setMaximum(15)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setProperty("value", 6)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_2.addWidget(self.horizontalSlider_2)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_3.setMaximum(15)
        self.horizontalSlider_3.setPageStep(1)
        self.horizontalSlider_3.setProperty("value", 9)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout_2.addWidget(self.horizontalSlider_3)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_4.setMaximum(9)
        self.horizontalSlider_4.setPageStep(1)
        self.horizontalSlider_4.setProperty("value", 5)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.verticalLayout_2.addWidget(self.horizontalSlider_4)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(490, 90, 91, 381))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_3)
        self.lcdNumber_3.setDigitCount(1)
        self.lcdNumber_3.setProperty("value", 4.0)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout_3.addWidget(self.lcdNumber_3)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_3)
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setProperty("value", 6.0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_3.addWidget(self.lcdNumber_2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget_3)
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setProperty("value", 9.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_3.addWidget(self.lcdNumber)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_3)
        self.lcdNumber_4.setDigitCount(2)
        self.lcdNumber_4.setProperty("value", 5.0)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout_3.addWidget(self.lcdNumber_4)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(120, 110, 20, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(360, 110, 20, 381))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(380, 60, 111, 451))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(4)
        self.spinBox.setProperty("value", 4)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_6.addWidget(self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.spinBox_2.setMaximum(15)
        self.spinBox_2.setProperty("value", 6)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_6.addWidget(self.spinBox_2)
        self.spinBox_3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.spinBox_3.setMaximum(15)
        self.spinBox_3.setProperty("value", 9)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_6.addWidget(self.spinBox_3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.spinBox_4.setMaximum(9)
        self.spinBox_4.setProperty("value", 5)
        self.spinBox_4.setObjectName("spinBox_4")
        self.verticalLayout_6.addWidget(self.spinBox_4)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(30, 480, 701, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(30, 50, 1261, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(30, 650, 701, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(20, 60, 20, 601))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(30, 60, 72, 31))
        self.label_13.setObjectName("label_13")
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(720, 60, 20, 601))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setGeometry(QtCore.QRect(580, 60, 20, 431))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(970, 60, 81, 31))
        self.label_14.setObjectName("label_14")
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setGeometry(QtCore.QRect(1280, 60, 20, 601))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 520, 701, 141))
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_2.setReadOnly(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(320, 490, 81, 31))
        self.label_15.setObjectName("label_15")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1190, 60, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1325, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action123 = QtWidgets.QAction(MainWindow)
        self.action123.setObjectName("action123")
        self.action123_3 = QtWidgets.QAction(MainWindow)
        self.action123_3.setObjectName("action123_3")
        self.action123_4 = QtWidgets.QAction(MainWindow)
        self.action123_4.setObjectName("action123_4")
        self.action123_6 = QtWidgets.QAction(MainWindow)
        self.action123_6.setObjectName("action123_6")
        self.menu.addAction(self.action123)
        self.menu.addAction(self.action123_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action123_6)
        self.menu_2.addAction(self.action123_4)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.horizontalSlider.valueChanged['int'].connect(self.lcdNumber_3.display)
        self.horizontalSlider_2.valueChanged['int'].connect(self.lcdNumber_2.display)
        self.horizontalSlider_3.valueChanged['int'].connect(self.lcdNumber.display)
        self.horizontalSlider_4.valueChanged['int'].connect(self.lcdNumber_4.display)
        self.action123_6.triggered.connect(MainWindow.close)
        self.horizontalSlider.valueChanged['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.horizontalSlider.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.horizontalSlider_2.setValue)
        self.horizontalSlider_2.valueChanged['int'].connect(self.spinBox_2.setValue)
        self.horizontalSlider_3.valueChanged['int'].connect(self.spinBox_3.setValue)
        self.spinBox_3.valueChanged['int'].connect(self.horizontalSlider_3.setValue)
        self.spinBox_4.valueChanged['int'].connect(self.horizontalSlider_4.setValue)
        self.horizontalSlider_4.valueChanged['int'].connect(self.spinBox_4.setValue)
        self.pushButton_7.clicked.connect(self.plainTextEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "koco语音助手"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "欢迎使用koco语音助手\n"
"目前那只支持文本信息\n"
"文本信息"))
        self.pushButton.setText(_translate("MainWindow", "测试"))
        self.pushButton_2.setText(_translate("MainWindow", "开始"))
        self.label_2.setText(_translate("MainWindow", "音色："))
        self.label.setText(_translate("MainWindow", "语速："))
        self.label_3.setText(_translate("MainWindow", "音调："))
        self.label_4.setText(_translate("MainWindow", "音量："))
        self.label_5.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "4"))
        self.label_10.setText(_translate("MainWindow", "15"))
        self.label_11.setText(_translate("MainWindow", "15"))
        self.label_12.setText(_translate("MainWindow", "9"))
        self.label_13.setText(_translate("MainWindow", "声音属性"))
        self.label_14.setText(_translate("MainWindow", "文本信息"))
        self.label_15.setText(_translate("MainWindow", "提示信息"))
        self.pushButton_7.setText(_translate("MainWindow", "清空"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.action123.setText(_translate("MainWindow", "打开"))
        self.action123.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action123_3.setText(_translate("MainWindow", "保存"))
        self.action123_3.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action123_4.setText(_translate("MainWindow", "关于"))
        self.action123_6.setText(_translate("MainWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

